version: "3"
services:
  app:
    container_name: docker-node-app
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"