name = "JAMstack Themes"
license = "MIT"
description = "A list of Themes and Starters for JAMstack Sites."
min_version = 0.51

[author]
  name = "JAMstack Themes"
  homepage = "https://www.jamstackthemes.dev"