version: "3.1"

services:
  db:
    image: postgres:11.1
    restart: always
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_DB: "${PG_DB}"

  adminer:
    image: adminer
    restart: always
    ports:
      - ${PG_ADMINER_PORT}:8080

  db_test:
    image: postgres:11.1
    restart: always
    ports:
      - "${PG_PORT_TEST}:5432"
    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_DB: "${PG_DB_TEST}"

  adminer_test:
    image: adminer
    restart: always
    ports:
      - ${PG_ADMINER_PORT_TEST}:8080
