baseURL = "http://christopherbiscardi.com/"
languageCode = "en-us"
title = "Chris Biscardi"
theme = "minimal"

[params]
    author = "Chris Biscardi"
    description = "Go, React, Products"
    githubUsername = "#christopherbiscardi"
    accent = "#1fa9f4"
    showBorder = true
    backgroundColor = "white"
    font = "interface, system-ui"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "swift", "javascript", "rust", "yaml", "lisp"]
    googleAnalytics = "UA-105803916-1"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/review/"
    name = "Reviews"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:chris@christopherbiscardi.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/christopherbiscardi/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/chrisbiscardi/"
    name = "twitter"
    weight = 3
