language: node_js
sudo: false
node_js:
  - 6

cache:
  directories:
    - ~/.npm
    - ~/.yarn-cache

git:
  depth: 10

before_install:
  # Use exact Node version.
  - nvm use $TRAVIS_NODE_VERSION

  # Setup package managers.
  - npm set loglevel error
  - npm set progress false
  - npm i -g yarn@0.16.1
  - yarn -V

install:
  # Install packages.
  - yarn

script:
  - ./bin/docdown ./node_modules/lodash/lodash.js output.md toc=categories url=https://github.com/lodash/lodash/blob/master/lodash.js
  - cat output.md
