-   id: prettier
    name: prettier
    entry: prettier --write
    language: node
    # From https://github.com/prettier/prettier/blob/133303f47a30f6b3e46ffdf9d5c2d6609d65c416/src/options.js#L32-L42
    files: \.(css|less|scss|html|ts|tsx|graphql|gql|json|js|jsx)$
