language: node_js
node_js:
  - "0.10"
before_install:
  - sudo apt-get update
  - sudo apt-get install imagemagick graphicsmagick
before_script:
  - psql -c 'create database hipush;' -U postgres
  - ./node_modules/.bin/gulp db:populate
addons:
  postgresql: "9.3"
