version: "3"

services:
  server:
    build: "../server"
    ports:
      - 3001:3001
    command: sh -c "yarn && yarn dev"
    volumes:
      - ../server:/usr/src/app

  ui:
    build: "../ui"
    ports:
      - 3000:3000
    command: sh -c "yarn && yarn dev"
    volumes:
      - ../ui:/usr/src/app

  db:
    image: postgres:11.1
    command: "-c logging_collector=on"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: changeme
      POSTGRES_DB: changeme

  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:5000
