on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 15 * *
name: Internal Requests
jobs:
  weekly-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Weekly News
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.GMOD_COMA_ID }}
          webhook_token: ${{ secrets.GMOD_COMA_TOKEN }}
          username: "Internal Requests"
          message: |
            Servus <@&198836006797967360> und <@&198835253568208896>
            
            Schaut bitte in die Internal Requests: https://www.elitepvpers.com/forum/internal-requests/
