on:
  schedule:
    - cron: 0 0 29 * *
name: Newsletter Reminder
jobs:
  newsletter-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Newsletter Reminder
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.COMA_ID }}
          webhook_token: ${{ secrets.COMA_TOKEN }}
          color: "#fcc200"
          username: "Reminder"
          message: |
            Der freundliche Bot sagt: Erinnerung an den Newsletter!
            
            Was hat sich am Progress Trello Board geändert? Welche Teamänderungen gab es?
            Neuigkeiten aus dem Forum oder besondere Community-Highlights?
