on:
  schedule:
    - cron: 20 16 * * TUE
name: Routine Reminder
jobs:
  routine-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: date-helper
        id: date-helper
        uses: ./.github/actions/date-helper
      - name: Send Routine No. 1
        uses: appleboy/discord-action@master
        if: steps.date-helper.outputs.routine == 1
        with:
          webhook_id: ${{ secrets.MEETING_INTERN_ID }}
          webhook_token: ${{ secrets.MEETING_INTERN_TOKEN }}
          username: "Reminder"
          message: |
            Auswertung von Ausschreibungen und Umfragen
            Follow-ups
            Kontrolle von Ultimaten
      - name: Send Routine No. 2
        uses: appleboy/discord-action@master
        if: steps.date-helper.outputs.routine == 2
        with:
          webhook_id: ${{ secrets.MEETING_INTERN_ID }}
          webhook_token: ${{ secrets.MEETING_INTERN_TOKEN }}
          username: "Reminder"
          message: |
            Auswertung von Ausschreibungen und Umfragen
            Follow-ups
            Kontrolle von Ultimaten
            Aktivit채t von Mods GMods CoMas Admins
            Bearbeitung der CA
            Projektfortschritte
      - name: Send Routine No. 3
        uses: appleboy/discord-action@master
        if: steps.date-helper.outputs.routine == 3
        with:
          webhook_id: ${{ secrets.MEETING_INTERN_ID }}
          webhook_token: ${{ secrets.MEETING_INTERN_TOKEN }}
          username: "Reminder"
          message: |
            Auswertung von Ausschreibungen und Umfragen
            Follow-ups
            Kontrolle von Ultimaten
      - name: Send Routine No. 4
        uses: appleboy/discord-action@master
        if: steps.date-helper.outputs.routine == 4
        with:
          webhook_id: ${{ secrets.MEETING_INTERN_ID }}
          webhook_token: ${{ secrets.MEETING_INTERN_TOKEN }}
          username: "Reminder"
          message: |
            Auswertung von Ausschreibungen und Umfragen
            Follow-ups
            Kontrolle von Ultimaten
            Aktivit채t von Mods GMods CoMas Admins
            Bearbeitung der CA
            Projektfortschritte
            Bearbeitung der Queues
            Kaufbelegkontrolle und Hack Inspections
            Nutzervorschl채ge und Feedback
            Newsletter
            Aktivit채t von CT CT-Leader
