on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * MON
name: Weekly News
jobs:
  weekly-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Weekly News
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.COMA_ID }}
          webhook_token: ${{ secrets.COMA_TOKEN }}
          username: "Weekly News"
          message: |
            Was gab es neues in der vergangenen Woche <@&198836006797967360> ?
            
            Wenn noch nicht die letzte Woche über getan teile bitte Neuigkeiten hier und im Admin Action Log mit :)
