language: node_js

node_js:
  - 12

notifications:
  email: false

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

git:
  depth: 5

branches:
  only:
  - master
  - stable

script:
  - yarn ci
  - yarn --cwd examples/typescript && yarn --cwd examples/typescript build
  - yarn --cwd examples/webpack/webpack4 && yarn --cwd examples/webpack/webpack4 build
  - yarn --cwd examples/webpack/webpack5 && yarn --cwd examples/webpack/webpack5 build


notifications:
  email: false
