version: '3.1'

services:

  db:
    image: postgres:11.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
