export default `
query collections($domainId: ID!, $checkoutId: String) {
  node(id: $domainId) {
    ... on DomainNode {
      id
      collections {
        edges {
          node {
            id
            name
            slug
            isAutogenerated
            productCount
            products(checkouts: $checkoutId) {
              edges {
                node {
                  id
                  name
                  gender
                  variantCount
                  description
                  quantity
                  slug
                  ... on ProductNode {
                    skus {
                      edges {
                        node {
                          width
                          height
                          length
                          salePrice
                          basePrice
                          orderSkus {
                            edges {
                              node {
                                sku {
                                  sku
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                  vendor {
                    id
                  }
                  images(orderBy: "orderingPosition") {
                    edges {
                      node {
                        id
                        image
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
`;
