on:
  schedule:
    - cron: 0 0 * * *
name: Site Showcase Validator workflow
jobs:
  gatsby-site-showcase-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: base_check
        name: Check if repo is gatsbyjs/gatsby
        run: |
          if [ "$GITHUB_REPOSITORY" = "gatsbyjs/gatsby" ]; then
            echo "::set-output name=base::true"
          fi
      - name: gatsby-site-showcase-validator
        if: steps.base_check.outputs.base == 'true'
        uses: ./.github/actions/gatsby-site-showcase-validator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
