engines:
 duplication:
   enabled: true
   config:
     languages:
     - javascript
 fixme:
   enabled: true
   config:
     strings:
     - FIXME
     - BUG
     - CUSTOM
ratings:
 paths:
 - "**.js"
exclude_paths:

