production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: xxx
  pool: 5
  username: xxx
  password: xxx
  socket: /tmp/mysql.sock

development_test:
  adapter: mysql2
  encoding: utf8
  database: xxx
  username: xxx
  password: xxx

development:
  development_test
