---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: docs/blog
  label: Blog Posts
  create: all
  match: "**/*.md"
  templates:
  - blog
- type: directory
  path: docs/docs
  label: Docs
  create: all
  match: "**/*.md"
  templates:
  - making-a-site-with-user-authentication
- type: document
  path: docs/blog/author.yaml
  label: Authors
- type: document
  path: docs/sites.yml
  label: Featured Sites
- type: document
  path: docs/starters.yml
  label: Starters
upload_dir: www/src/uploads
public_path: "/src/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: npm run forestry:preview
  publish_command: gatsby build
  preview_env:
  - BUILD_DIR=www/
  preview_output_directory: public
  output_directory: www/public
