version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/src"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5858:5858"
    links:
      - "db"
    depends_on:
      - db
    environment:
      NODE_ENV: dev
      PGPASSWORD: "${PGPASSWORD}"
      PGUSER: "${PGUSER}"
      PGDB: "${PGDB}"
    command: npm run _dev
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_DB: "${PGDB}"

  adminer:
    image: adminer
    ports:
      - 8080:8080
