orbs:
  win: circleci/windows@2.2.0
  slack: circleci/slack@3.4.1

executors:
  node:
    parameters:
      image:
        type: string
        # First 10.x LTS release, but old Yarn
        default: "10.13"
    docker:
      - image: circleci/node:<< parameters.image >>
  node_10_19:
    parameters:
      image:
        type: string
        # More recent Yarn binary
        default: "10.19"
    docker:
      - image: circleci/node:<< parameters.image >>

aliases:
  e2e-executor: &e2e-executor
    docker:
      - image: cypress/browsers:node10.16.0-chrome76

  restore_cache: &restore_cache
    restore_cache:
      name: Restore node_modules cache
      keys:
        - yarn-cypress-cache-{{ checksum "yarn.lock" }}

  install_node_modules: &install_node_modules
    run:
      name: Install node modules
      command: yarn --frozen-lockfile

  persist_cache: &persist_cache
    save_cache:
      name: Save node modules cache
      key: yarn-cypress-cache-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache

  attach_to_bootstrap: &attach_to_bootstrap
    attach_workspace:
      at: ./

  ignore_master: &ignore_master
    filters:
      branches:
        ignore:
          - master

  ignore_docs: &ignore_docs
    filters:
      branches:
        ignore:
          - /docs.+/
          - /blog.+/

  test_template: &test_template
    steps:
      - checkout
      - run: ./scripts/assert-changed-files.sh "packages/*|.circleci/*"
      - <<: *attach_to_bootstrap
      - run: yarn list react
      - run:
          command: node --max-old-space-size=2048 ./node_modules/.bin/jest -w 1 --ci
          environment:
            GENERATE_JEST_REPORT: true
            JEST_JUNIT_OUTPUT_DIR: ./test-results/jest-node/
            JEST_JUNIT_OUTPUT_NAME: results.xml
      - store_test_results:
          path: ./test-results/jest-node/

  e2e-test-workflow: &e2e-test-workflow
    filters:
      branches:
        ignore:
          - master
          - /docs.+/
          - /blog.+/
    requires:
      - lint
      - typecheck
      - unit_tests_node10

  e2e_tests_production_runtime_alias: &e2e_tests_production_runtime_alias
    <<: *e2e-executor
    parameters:
      nightly:
        type: boolean
        default: false
    steps:
      - e2e-test:
          test_path: e2e-tests/production-runtime
          test_command: CYPRESS_PROJECT_ID=is8aoq CYPRESS_RECORD_KEY=cb4708d2-1578-4665-9a07-c59f8db28d91 yarn test && CYPRESS_PROJECT_ID=htpvkv CYPRESS_RECORD_KEY=0d734841-c613-41d2-86e5-df0b5968f93f yarn test:offline
          skip_file_change_test: << parameters.nightly >>
      - notify-status:
          condition: << parameters.nightly >>

  e2e_tests_development_runtime_alias: &e2e_tests_development_runtime_alias
    <<: *e2e-executor
    parameters:
      nightly:
        type: boolean
        default: false
    environment:
      CYPRESS_PROJECT_ID: s3j3qj
      CYPRESS_RECORD_KEY: 3904ca0c-bc98-47d9-8371-b68c5e81fb9b
    steps:
      - e2e-test:
          test_path: e2e-tests/development-runtime
          skip_file_change_test: << parameters.nightly >>
      - notify-status:
          condition: << parameters.nightly >>

  e2e_tests_gatsby-image_alias: &e2e_tests_gatsby-image_alias
    <<: *e2e-executor
    parameters:
      nightly:
        type: boolean
        default: false
    environment:
      CYPRESS_PROJECT_ID: ave32k
      CYPRESS_RECORD_KEY: fb3cb6e0-a0f9-48b2-aa9a-95e8ef150a85
    steps:
      - e2e-test:
          test_path: e2e-tests/gatsby-image
          skip_file_change_test: << parameters.nightly >>
      - notify-status:
          condition: << parameters.nightly >>

commands:
  notify-status:
    parameters:
      condition:
        type: boolean
        default: false
    steps:
      - when:
          condition: << parameters.condition >>
          steps:
            - slack/status:
              channel: eng-react-integration-status

  e2e-test:
    parameters:
      skip_file_change_test:
        type: boolean
        default: false
      trigger_pattern:
        type: string
        default: "packages/*|.circleci/*"
      test_path:
        type: string
      test_command:
        type: string
        default: "yarn test"
    steps:
      - checkout
      # In case of failure, add these steps again. Cache probably got deleted
      #- <<: *restore_cache
      #- <<: *install_node_modules
      #- <<: *persist_cache
      - unless:
          condition: << parameters.skip_file_change_test >>
          steps:
            - run: ./scripts/assert-changed-files.sh "<< parameters.trigger_pattern >>|<< parameters.test_path >>/*"

      - <<: *attach_to_bootstrap
      - run:
          name: Run tests (using defaults)
          command: ./scripts/e2e-test.sh "<< parameters.test_path >>" "<< parameters.test_command >>"

version: 2.1

jobs:
  bootstrap:
    executor: node
    steps:
      - checkout
      - run: ./scripts/assert-changed-files.sh "packages/*|(e2e|integration)-tests/*|.circleci/*"
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - run: yarn bootstrap -- concurrency=2
      # Persist the workspace again with all packages already built
      - persist_to_workspace:
          root: ./
          paths:
            - "*"

  lint:
    executor: node
    steps:
      - checkout
      # installation of dependencies takes a while because of the 100 packages we have inside the monorepo
      # Linting only needs the root packages, we remove the workspace and only install root packages
      - run:
          name: "remove workspaces from package.json"
          command: |
            sed -i ':a;N;$!ba;s/,\n\s*"workspaces":\s\[[^]]*]//g' package.json
      - <<: *install_node_modules
      - run: yarn lint:code
      - run: yarn lint:docs
      - run: yarn lint:other

  typecheck:
    executor: node
    steps:
      - checkout
      # We should always assert on master
      - run: ./scripts/assert-changed-files.sh "packages/*|.circleci/*"
      - <<: *attach_to_bootstrap
      - run: yarn typecheck
      - run: yarn check-repo-fields

  unit_tests_node10:
    executor: node
    <<: *test_template

  unit_tests_node12:
    executor:
      name: node
      image: "12"
    <<: *test_template

  unit_tests_node14:
    executor:
      name: node
      image: "14"
    <<: *test_template

  unit_tests_www:
    executor: node
    steps:
      - checkout
      - run:
          command: yarn
          working_directory: ~/project/www
      - run:
          command: yarn test
          working_directory: ~/project/www

  integration_tests_long_term_caching:
    executor: node
    steps:
      - e2e-test:
          test_path: integration-tests/long-term-caching

  integration_tests_cache_resilience:
    executor: node
    steps:
      - e2e-test:
          test_path: integration-tests/cache-resilience

  integration_tests_gatsby_pipeline:
    executor: node
    steps:
      - e2e-test:
          test_path: integration-tests/gatsby-pipeline

  integration_tests_gatsby_cli:
    executor: node
    steps:
      - e2e-test:
          test_path: integration-tests/gatsby-cli
          trigger_pattern: packages/gatsby-cli/*|packages/gatsby/*|integration-tests/gatsby-cli/*

  integration_tests_structured_logging:
    executor: node
    steps:
      - e2e-test:
          test_path: integration-tests/structured-logging

  integration_tests_artifacts:
    executor: node
    steps:
      - e2e-test:
          test_path: integration-tests/artifacts

  e2e_tests_path-prefix:
    <<: *e2e-executor
    environment:
      CYPRESS_PROJECT_ID: pzj19c
      CYPRESS_RECORD_KEY: c9ea1b91-eed6-4bac-be41-eccd75a48969
    steps:
      - e2e-test:
          test_path: e2e-tests/path-prefix

  e2e_tests_pnp:
    executor: node_10_19
    steps:
      - checkout
      - run: ./scripts/assert-changed-files.sh "packages/*|.circleci/*"
      - <<: *attach_to_bootstrap
      - run:
          command: cp -r ./starters/default ./e2e-tests/gatsby-pnp
          working_directory: ~/project
      - run:
          command: touch yarn.lock
          working_directory: ~/project/e2e-tests/gatsby-pnp
      - run: # Quick upgrade to the v2 (any version, we just need the real set version)
          command: yarn policies set-version berry
          working_directory: ~/project/e2e-tests/gatsby-pnp
      - run: # Pins the Yarn version
          command: yarn set version 2.0.0-rc.32
          working_directory: ~/project/e2e-tests/gatsby-pnp
      - run: # Forces to use the local packages
          command: yarn link --all --private ../..
          working_directory: ~/project/e2e-tests/gatsby-pnp
      - run:
          command: yarn install
          working_directory: ~/project/e2e-tests/gatsby-pnp
      - run:
          command: yarn add start-server-and-test@^1.11.0
          working_directory: ~/project/e2e-tests/gatsby-pnp
      - run:
          command: yarn build
          working_directory: ~/project/e2e-tests/gatsby-pnp
      - run:
          command: 'DEBUG=start-server-and-test yarn start-server-and-test "yarn develop 2>&1 | tee log.txt" :8000 "! cat log.txt | grep -E ''ERROR #|Require stack:''"'
          working_directory: ~/project/e2e-tests/gatsby-pnp

  e2e_tests_gatsby-image:
    <<: *e2e_tests_gatsby-image_alias

  e2e_tests_gatsby-image_with_experimental_react:
    <<: *e2e_tests_gatsby-image_alias

  e2e_tests_gatsby-image_with_next_react:
    <<: *e2e_tests_gatsby-image_alias

  e2e_tests_development_runtime:
    <<: *e2e_tests_development_runtime_alias

  e2e_tests_development_runtime_with_experimental_react:
    <<: *e2e_tests_development_runtime_alias

  e2e_tests_development_runtime_with_next_react:
    <<: *e2e_tests_development_runtime_alias

  e2e_tests_production_runtime:
    <<: *e2e_tests_production_runtime_alias

  e2e_tests_production_runtime_with_experimental_react:
    <<: *e2e_tests_production_runtime_alias

  e2e_tests_production_runtime_with_next_react:
    <<: *e2e_tests_production_runtime_alias

  themes_e2e_tests_development_runtime:
    <<: *e2e-executor
    environment:
      CYPRESS_PROJECT_ID: 9parq5
      CYPRESS_RECORD_KEY: 3fb49000-4143-4bd8-9ab4-219389060910
    steps:
      - e2e-test:
          test_path: e2e-tests/themes/development-runtime
          test_command: yarn test

  themes_e2e_tests_production_runtime:
    <<: *e2e-executor
    environment:
      CYPRESS_PROJECT_ID: c9rs27
      CYPRESS_RECORD_KEY: e4e7b3b8-e1e7-4a74-a0c9-9ac76585236b
    steps:
      - e2e-test:
          test_path: e2e-tests/themes/production-runtime
          test_command: yarn test

  mdx_e2e_tests:
    <<: *e2e-executor
    steps:
      - e2e-test:
          test_path: e2e-tests/mdx
          test_command: yarn test

  starters_validate:
    executor: node
    steps:
      - checkout
      - run: ./scripts/assert-changed-files.sh "starters/*|.circleci/*"
      - run: sh ./scripts/validate-starters.sh "starters/*"

  starters_publish:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - run: yarn markdown
      - run: sudo apt-get update && sudo apt-get install jq # jq is helpful for parsing json
      - run: git config --global user.name "GatsbyJS Bot"
      - run: git config --global user.email "core-team@gatsbyjs.com"
      - run: sh ./scripts/publish-starters.sh "starters/*"

  update_i18n_source:
    executor: node
    steps:
      - checkout
      - run: git config --global user.name "GatsbyJS Bot"
      - run: git config --global user.email "core-team@gatsbyjs.com"
      - run:
          command: yarn
          working_directory: ~/project/scripts/i18n
      - run:
          command: yarn run update-source
          working_directory: ~/project/scripts/i18n

  sync_translation_repo:
    executor: node
    steps:
      - checkout
      - run: git config --global user.name "GatsbyJS Bot"
      - run: git config --global user.email "core-team@gatsbyjs.com"
      - run:
          command: yarn
          working_directory: ~/project/scripts/i18n
      - run:
          command: yarn run-all sync
          working_directory: ~/project/scripts/i18n

  windows_unit_tests:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      # Restoring cache takes as long as installing node modules, so skipping
      # - restore_cache:
      #     keys:
      #       - yarn-packages-v2-{{ checksum "yarn.lock" }}
      #       - yarn-packages-v2-
      - run:
          name: Install node modules
          command: yarn --frozen-lockfile
      # Caching is slow, so disabling
      # - save_cache:
      #     paths:
      #       - C:\Users\circleci\AppData\Local\Yarn\Cache
      #     key: yarn-packages-v2-{{ checksum "yarn.lock" }}
      - run:
          command: ./scripts/assert-changed-files.sh "packages/*|(e2e|integration)-tests/*|.circleci/*"
          shell: bash.exe
      - run: yarn npm-run-all -s check-versions "lerna-prepare --concurrency=4 --stream"
      - run:
          name: "Run Tests"
          command: yarn jest -w 1 --ci

  bootstrap-with-experimental-react:
    executor: node
    parameters:
      version:
        type: string
        default: "next"
    steps:
      - checkout
      - run:
          name: "Update React to prerelease"
          command: "REACT_CHANNEL=<< parameters.version >> node ./scripts/upgrade-react"
      - run: yarn install
      - run: yarn bootstrap -- concurrency=2
      - run: yarn list react
      - persist_to_workspace:
          root: ./
          paths:
            - "*"

workflows:
  version: 2

  weekly-i18n-sync:
    triggers:
      - schedule:
          cron: "0 1 * * 6"
          filters:
            branches:
              only:
                - master
    jobs:
      - sync_translation_repo

  weekly-node-14:
    triggers:
      - schedule:
          cron: "0 1 * * 6"
          filters:
            branches:
              only:
                - master
    jobs:
      - unit_tests_node14

  nightly-react-next:
    triggers:
      - schedule:
          cron: "0 0 * * 1,2,3,4,5"
          filters:
            branches:
              only:
                - master
    jobs:
      - bootstrap-with-experimental-react:
          version: "next"
      - e2e_tests_gatsby-image_with_next_react:
          nightly: true
          requires:
            - bootstrap-with-experimental-react
      - e2e_tests_development_runtime_with_next_react:
          nightly: true
          requires:
            - bootstrap-with-experimental-react
      - e2e_tests_production_runtime_with_next_react:
          nightly: true
          requires:
            - bootstrap-with-experimental-react
  nightly-react-experimental:
    triggers:
      - schedule:
          cron: "0 0 * * 1,2,3,4,5"
          filters:
            branches:
              only:
                - master
    jobs:
      - bootstrap-with-experimental-react:
          version: "experimental"
      - e2e_tests_gatsby-image_with_experimental_react:
          nightly: true
          requires:
            - bootstrap-with-experimental-react
      - e2e_tests_development_runtime_with_experimental_react:
          nightly: true
          requires:
            - bootstrap-with-experimental-react
      - e2e_tests_production_runtime_with_experimental_react:
          nightly: true
          requires:
            - bootstrap-with-experimental-react

  build-test:
    jobs:
      - bootstrap
      - lint
      - typecheck:
          requires:
            - bootstrap
      - windows_unit_tests:
          <<: *ignore_docs
          requires:
            - lint
      - unit_tests_node10:
          <<: *ignore_docs
          requires:
            - lint
            - typecheck
            - bootstrap
      - unit_tests_node12:
          <<: *ignore_docs
          requires:
            - lint
            - typecheck
            - bootstrap
      - unit_tests_www:
          requires:
            - lint
            - typecheck
            - bootstrap
      - integration_tests_long_term_caching:
          <<: *e2e-test-workflow
      - integration_tests_cache_resilience:
          <<: *e2e-test-workflow
      - integration_tests_gatsby_pipeline:
          <<: *e2e-test-workflow
      - integration_tests_structured_logging:
          <<: *e2e-test-workflow
      - integration_tests_artifacts:
          <<: *e2e-test-workflow
      - integration_tests_gatsby_cli:
          requires:
            - bootstrap
      - e2e_tests_pnp:
          <<: *e2e-test-workflow
      - e2e_tests_path-prefix:
          <<: *e2e-test-workflow
      - e2e_tests_gatsby-image:
          <<: *e2e-test-workflow
      - e2e_tests_development_runtime:
          <<: *e2e-test-workflow
      - e2e_tests_production_runtime:
          <<: *e2e-test-workflow
      - themes_e2e_tests_production_runtime:
          <<: *e2e-test-workflow
      - themes_e2e_tests_development_runtime:
          <<: *e2e-test-workflow
      - mdx_e2e_tests:
          <<: *e2e-test-workflow
      - starters_validate:
          <<: *ignore_master
      - starters_publish:
          filters:
            branches:
              only:
                - master
      - update_i18n_source:
          filters:
            branches:
              only:
                - master
