version: '2'

services:
  neo4j:
    image: bitnami/neo4j:3.4.10
    volumes:
      - ./volumes/neo4j:/bitnami
      - ./volumes/neo4j/plugins:/bitnami/neo4j/plugins
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    depends_on:
      - fix-neo4j-permissions

  neo4j-test:
    image: bitnami/neo4j:3.4.10
    volumes:
      - ./tmp/volumes/neo4j-test:/bitnami
      - ./volumes/neo4j/plugins:/bitnami/neo4j/plugins
    ports:
      - '17474:7474'
      - '17473:7473'
      - '17687:7687'
    depends_on:
      - fix-neo4j-test-permissions

  fix-neo4j-permissions:
    image: bitnami/neo4j:3.4.10
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - ./volumes/neo4j/neo4j:/bitnami/neo4j

  fix-neo4j-test-permissions:
    image: bitnami/neo4j:3.4.10
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - ./tmp/volumes/neo4j-test/neo4j:/bitnami/neo4j
