version: "3"
services:
  web:
    build: .
    volumes:
      - ".:/home/app/src"
      - "/home/app/src/node_modules"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5858:5858"
    links:
      - "db"
    depends_on:
      - db
    environment:
      NODE_ENV: dev
    command: yarn run dev
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_DB: "${PG_DB}"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
