# .travis.yml
language: ruby
rvm:
  - 2.2.4
env:
  - DB=postgresql
install:
  - bundle install --without development --jobs=3 --retry=3 --deployment
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database ox_mp2_test' -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
