environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"

build: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - if "%nodejs_version%" == "7" (
      npm run lint &&
      npm run coverage  &&
      npm run test-doclint
    ) else (
      npm run unit-node6
    )
