# .travis.yml
language: node_js

node_js:
  - '4'
  - '6'

before_script:
  - psql -c "create database objection_rest_test;" -U postgres
  - mysql -e "create database objection_rest_test;"

after_script:
  - npm run-script coveralls

notifications:
  email: false

addons:
  postgresql: '9.4'
