version: "3.1"

services:
  db:
    image: postgres:11.1
    command: "-c logging_collector=on"
    restart: always
    ports:
      - "${PORT_PG}:5432"
    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_DB: "${PG_DB}"

  adminer:
    image: adminer
    restart: always
    ports:
      - ${PORT_PG_ADMINER}:8080
